abibas_shoes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user, edit_product, delete_product, show_products, add_product_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),
    path('products/', show_products, name='show_products'),
    path('create-ajax', add_product_ajax, name='add_product_ajax'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    type = models.CharField(max_length=50)
    materials = models.CharField(max_length=50)

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "type", "materials"]

    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)

    def clean_type(self):
        type = self.cleaned_data["type"]
        return strip_tags(type)
    
    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)
    
    def clean_materials(self):
        materials = self.cleaned_data["materials"]
        return strip_tags(materials)

main/views.py
from django.shortcuts import render, redirect, reverse
from main.forms import ProductForm
from main.models import Product
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags

@login_required(login_url='/login')
def show_main(request):
    #products = Product.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'class': 'PBP F',
        #'products': products,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return redirect('main:show_products')

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
        user = form.get_user()
        login(request, user)
        response = HttpResponseRedirect(reverse("main:show_main"))
        response.set_cookie('last_login', str(datetime.datetime.now()))
        return response
      
      else:
        messages.error(request, "Invalid username or password. Please try again.")

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product berdasarkan id
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_products'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get mood berdasarkan id
    product = Product.objects.get(pk = id)
    # Hapus mood
    product.delete()
    # reload page
    return HttpResponseRedirect(reverse('main:show_products'))

def show_products(request):
    return render(request, 'products.html')

@csrf_exempt
@require_POST
def add_product_ajax(request):
    id = request.POST.get("id")
    name = strip_tags(request.POST.get("name"))
    price = request.POST.get("price")
    description = strip_tags(request.POST.get("description"))
    type = strip_tags(request.POST.get("type"))
    materials = strip_tags(request.POST.get("materials"))
    user = request.user

    new_product = Product(
        id=id, name=name,
        price=price, description=description,
        type=type, materials=materials,
        user=user
    )
    new_product.save()

    return HttpResponse(b"CREATED", status=201)

main/templates/card_product.html
<div class="col-8 col-lg-4 col-xl-3">

    <div class="card border-8">

        <div class="card-body text-center py-4">

        <h4 class="card-title">{{product.name}}</h4>

        <p class="lead card-subtitle">{{product.type}}</p>

        <p class="lead card-subtitle">{{product.materials}}</p>

        <p class="display-5 my-4 text-primary fw-bold">Rp{{product.price}}K</p>

        <p class="card-text mx-5 text-muted d-none d-lg-block">{{product.description}}</p>

        <a href="{% url 'main:edit_product' product.pk %}" class="btn btn-outline-primary btn-lg mt-3">Edit</a>

        <a href="{% url 'main:delete_product' product.pk %}" class="btn btn-outline-primary btn-lg mt-3">Delete</a>

        </div>

    </div>

</div>

main/templates/create_product.html
{% extends 'base.html' %}

{% block meta %}
<title>Add New Product</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="container mt-5">
    <h1 class="text-center">Add New Product</h1>

    <form method="POST" class="mt-4">
    {% csrf_token %}
    <div class="mb-3"> <!-- This wrapper can be kept for grouping all fields -->
        {% for field in form %}
            <div class="mb-3"> 
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                <input type="{{ field.field.widget.type }}" name="{{ field.name }}" id="{{ field.id_for_label }}" 
                       class="form-control" value="{{ field.value|default:'' }}" 
                       {% if field.is_required %} required {% endif %}>
                {% if field.errors %}
                    <div class="text-danger">
                        {% for error in field.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <div class="d-flex justify-content-center">
        <input class="btn btn-success" type="submit" value="Add Product" />
    </div>
</form>
</div>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}
{% block meta %}
<title>Edit Product</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="container mt-5">
    <h1 class="text-center">Edit Product</h1>

    <form method="POST" class="mt-4">
        {% csrf_token %}
        <div class="mb-3">
            {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    <input type="{{ field.field.widget.type }}" name="{{ field.name }}" id="{{ field.id_for_label }}" 
                           class="form-control" value="{{ field.value|default:'' }}" 
                           {% if field.is_required %} required {% endif %}>
                    {% if field.errors %}
                        <div class="text-danger">
                            {% for error in field.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        <div class="d-flex justify-content-center">
            <input class="btn btn-warning" type="submit" value="Edit Product" />
        </div>
    </form>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="login mt-5">
        <h1 class="text-center">Login</h1>

        <form method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" name="username" class="form-control" id="username" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" name="password" class="form-control" id="password" required>
            </div>
            <div class="d-flex justify-content-center">
                <input class="btn btn-primary" type="submit" value="Sign In" />
            </div>
        </form>

        {% if messages %}
        <div class="alert alert-danger mt-3">
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        
        <p class="text-center mt-3">Don't have an account yet? <a href="{% url 'main:register' %}" class="link-primary">Register Now</a></p>
    </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% block content %}
{% include 'navbar.html' %}

<div class="container mt-5">
    <div class="text-center">
        <!-- Abibas heading -->
        <h1 class="display-4 text-dark fw-bold">Abibas</h1>

        <!-- Tagline -->
        <h2 class="display-5 text-primary fw-light">Run Anywhere, Fun Everywhere</h2>
        <p class="lead text-muted">The best place to find high-quality shoes at great prices!</p>
    </div>

    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card bg-light border-primary shadow-sm">
                <div class="card-body">
                    <h5 class="card-title text-primary">User Information</h5>
                    <p class="card-text">
                        <strong>Name:</strong> {{ name }}<br>
                        <strong>Class:</strong> {{ class }}<br>
                        <strong>Last Login:</strong> {{ last_login }}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/products.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Products</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center">
        <h1 class="text-center">Products</h1>
        <a href="{% url 'main:create_product' %}" class="btn btn-primary">Add Product</a>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Add New Product by AJAX
        </button>
    </div>

    <div id="product_cards"></div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header border-bottom-0">
                    <h5 class="modal-title" id="exampleModalLabel">Add New Product</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="productForm">
                        <div class="mb-4">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" id="name" name="name" class="form-control" placeholder="Enter the product name" required>
                        </div>
                        <div class="mb-4">
                            <label for="price" class="form-label">Price</label>
                            <input type="number" id="price" name="price" class="form-control" placeholder="Enter the price" required>
                        </div>
                        <div class="mb-4">
                            <label for="description" class="form-label">Description</label>
                            <textarea id="description" name="description" rows="3" class="form-control" placeholder="Enter the product description" required></textarea>
                        </div>
                        <div class="mb-4">
                            <label for="type" class="form-label">Type</label>
                            <input type="text" id="type" name="type" class="form-control" placeholder="Enter the shoes type" required>
                        </div>
                        <div class="mb-4">
                            <label for="materials" class="form-label">Materials</label>
                            <input id="materials" name="materials" class="form-control" placeholder="Enter the shoes materials" required>
                        </div>
                    </form>
                </div>
                <div class="modal-footer border-top-0">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" id="submitProduct" form="productForm" class="btn btn-primary">Save</button>
                </div>
            </div>
        </div>
    </div>



</div>

<script>

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
        method: "POST",
        body: new FormData(document.querySelector('#productForm')),
        })
        .then(response => refreshProducts())
        
        document.getElementById("productForm").reset(); 
        //document.querySelector("[data-modal-toggle='crudModal']").click();
        const modal = bootstrap.Modal.getInstance(document.getElementById('exampleModal'));
        modal.toggle();

        modal.dispose(); 
        const backdrop = document.querySelector('.modal-backdrop');
        if (backdrop) {
            backdrop.remove();
            document.body.classList.remove('modal-open');  // Remove the body class to restore focus
        }
        return false;
    }

    async function getProducts(){
        return fetch("{% url 'main:show_json' %}").then((res) => res.json())
    }

    async function refreshProducts() {
        document.getElementById("product_cards").innerHTML = "";
        document.getElementById("product_cards").className = "";
        const products = await getProducts();
        let htmlString = "";
        let classNameString = "";

        if (products.length === 0) {
            classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
            htmlString = `
                <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 24rem;">
                    <img src="{% static 'image/sedih-banget.png' %}" alt="No products" class="mb-4" style="width: 8rem; height: 8rem;">
                    <p class="text-muted">No products available in your store.</p>
                </div>
            `;
        }
        else {
            classNameString = "row row-cols-1 row-cols-sm-2 row-cols-lg-3 g-4"
            products.forEach((item) => {
                htmlString += `
                <div class="col-8 col-lg-4 col-xl-3">

                    <div class="card border-8">

                        <div class="card-body text-center py-4">

                        <h4 class="card-title">${item.fields.name}</h4>

                        <p class="lead card-subtitle">${item.fields.type}</p>

                        <p class="lead card-subtitle">${item.fields.materials}</p>

                        <p class="display-5 my-4 text-primary fw-bold">Rp${item.fields.price}K</p>

                        <p class="card-text mx-5 text-muted d-none d-lg-block">${item.fields.description}</p>
                        
                        

                        <a href="/edit-product/${item.pk}" class="btn btn-outline-primary btn-lg mt-3">Edit</a>

                        <a href="/delete/${item.pk}" class="btn btn-outline-primary btn-lg mt-3">Delete</a>

                        </div>

                    </div>

                </div>
                `;
            });
        }
        document.getElementById("product_cards").className = classNameString;
        document.getElementById("product_cards").innerHTML = htmlString;
    }
refreshProducts();

document.getElementById("productForm").addEventListener("submit", (e) => {
    e.preventDefault();
    addProduct();
})
</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="login mt-5">
        <h1 class="text-center">Register</h1>

        <form method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_username" class="form-label">Username</label>
                <input type="text" name="username" class="form-control" id="id_username" value="{{ form.username.value }}" required>
                {% if form.username.errors %}
                <div class="text-danger">
                    {{ form.username.errors }}
                </div>
                {% endif %}
            </div>

            <div class="mb-3">
                <label for="id_password1" class="form-label">Password</label>
                <input type="password" name="password1" class="form-control" id="id_password1" required>
                {% if form.password1.errors %}
                <div class="text-danger">
                    {{ form.password1.errors }}
                </div>
                {% endif %}
            </div>

            <div class="mb-3">
                <label for="id_password2" class="form-label">Confirm Password</label>
                <input type="password" name="password2" class="form-control" id="id_password2" required>
                {% if form.password2.errors %}
                <div class="text-danger">
                    {{ form.password2.errors }}
                </div>
                {% endif %}
            </div>

            <div class="d-flex justify-content-center">
                <input class="btn btn-primary" type="submit" value="Register" />
            </div>
        </form>

        {% if messages %}
        <div class="alert alert-danger mt-3">
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        
        <p class="text-center mt-3">Already have an account? <a href="{% url 'main:login' %}" class="link-primary">Login here</a></p>
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block meta %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock meta %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    <!-- font text -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">


    <!-- Link ke global.css -->
    <link rel="stylesheet" href="{% static 'css/global.css' %}">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

  </head>

  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Abibas</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'main:show_main' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:show_products' %}">Products</a>
                </li>
            </ul>
            <a href="{% url 'main:logout' %}" class="btn btn-danger" style="margin-left: auto;">Logout</a>
        </div>
    </div>
</nav>